---
- name: Install OpenJDK
  apt:
    name: openjdk-11-jdk
    state: present

- name: Download Kafka
  ansible.builtin.get_url:
    url: "https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_{{ kafka_version }}.tgz"
    dest: "/tmp/kafka_{{ kafka_version }}.tgz"

- name: Extract Kafka
  ansible.builtin.unarchive:
    src: "/tmp/kafka_{{ kafka_version }}.tgz"
    dest: "{{ kafka_home }}"
    remote_src: yes
    creates: "{{ kafka_home }}/bin/kafka-server-start.sh"

- name: Configure server.properties
  template:
    src: server.properties.j2
    dest: "{{ kafka_config_file }}"
  notify: Restart Kafka Service

  handlers:
  - name: Restart Kafka Service
    ansible.builtin.systemd:
      name: kafka
      state: restarted
