---
- name: Install OpenJDK
  apt:
    name: openjdk-11-jdk
    state: present

- name: Download Kafka and Unzip 
  unarchive:
    src: https://dlcdn.apache.org/kafka/3.1.0/kafka_2.13-3.1.0.tgz
    dest: "{{kafka_config_dir}}"
    mode: 0755
    remote_src: yes

handlers:
  - name: Configure server.properties
    template:
      src: server.properties.j2
      dest: "{{ kafka_config_file }}"
    notify: Restart Kafka Service
  
  - name: Restart Kafka Service
    ansible.builtin.systemd:
      name: kafka
      state: restarted
